import uuid
from enum import Enum

from sqlalchemy import CheckConstraint, Enum as SAEnum
from sqlalchemy import ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from ..base import Base
from .bloom import BloomLevel
from .mixins import IdMixin, TimestampMixin


class QuestionType(str, Enum):
    MCQ = "MCQ"
    SHORT_ANSWER = "SHORT_ANSWER"
    LONG_ANSWER = "LONG_ANSWER"
    TRUE_FALSE = "TRUE_FALSE"


class CustomQuestion(IdMixin, TimestampMixin, Base):
    """A School Admin-authored question, added directly to that school's
    own bank rather than generated by DeterministicContentGenerator - the
    first question content in this product that isn't produced by the
    generator. Tagged with the full curriculum hierarchy (Subject ->
    Chapter -> Topic, same as the global catalog) plus either one specific
    Class (a single grade+section, e.g. "Class 10 · A") or a whole `grade`
    (every section in that grade at this school) - exactly one of the two,
    never both/neither (see the check constraint below). Content common
    across sections of the same grade doesn't need to be duplicated once
    per section. School-scoped (not global like Subject/Chapter/Topic),
    since this is a School Admin's own content, not shared across schools.
    Surfaced read-only in the existing GET /school/question-bank alongside
    generated questions (source="CUSTOM"), and separately create/edit/
    delete/bulk-import-able via /school/custom-questions - see
    requirements.md's custom-question entry.
    """

    __tablename__ = "custom_questions"
    __table_args__ = (
        CheckConstraint(
            "(class_id IS NOT NULL AND grade IS NULL) OR (class_id IS NULL AND grade IS NOT NULL)",
            name="custom_questions_class_xor_grade",
        ),
    )

    school_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("schools.id"))
    # Exactly one of class_id/grade is set - see this class's docstring.
    class_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("classes.id"), nullable=True)
    grade: Mapped[int | None] = mapped_column(Integer, nullable=True)
    subject_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("subjects.id"))
    chapter_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("chapters.id"))
    # Nullable - some content is chapter-level only, not topic-specific.
    topic_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("topics.id"), nullable=True)
    bloom_level: Mapped[BloomLevel] = mapped_column(SAEnum(BloomLevel, name="bloom_level"))
    question_type: Mapped[QuestionType] = mapped_column(SAEnum(QuestionType, name="question_type"))
    text: Mapped[str] = mapped_column(Text)
    # Only meaningful for MCQ/TRUE_FALSE - the selectable choices; `answer`
    # below must match one of these exactly (enforced in
    # CreateCustomQuestionIn's validator, not here). NULL for
    # SHORT_ANSWER/LONG_ANSWER, which have no fixed choices.
    options: Mapped[list[str] | None] = mapped_column(JSONB, nullable=True)
    answer: Mapped[str] = mapped_column(Text)
    created_by: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"))
    # NULL = added straight to the school's general question bank (the
    # default). A School Admin/Teacher can instead name a set (e.g. "Mid-
    # term practice") to group related questions - purely a label, not a
    # separate table, since a school's own custom-question volume never
    # needs indexed lookup beyond a simple equality filter.
    collection_name: Mapped[str | None] = mapped_column(String, nullable=True)
