"""homework generated insights

Revision ID: 012bd47f8e6b
Revises: e8a9c310315a
Create Date: 2026-09-15 14:13:42.106807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012bd47f8e6b'
down_revision: Union[str, None] = 'e8a9c310315a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('insight_what_needs_understanding', sa.Text(), nullable=True))
    op.add_column('homework', sa.Column('insight_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('homework', sa.Column('insight_key_idea_title', sa.Text(), nullable=True))
    op.add_column('homework', sa.Column('insight_key_idea_body', sa.Text(), nullable=True))
    op.add_column('homework', sa.Column('insight_connection_prompt', sa.Text(), nullable=True))
    op.add_column('homework', sa.Column('insight_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Note: autogenerate also detected a pre-existing, unrelated drop of
    # 'ix_practice_bank_entries_student_id' (model/DB drift predating this
    # change) - deliberately left out of this migration, which is scoped
    # to Homework's new insight columns only.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework', 'insight_generated_at')
    op.drop_column('homework', 'insight_connection_prompt')
    op.drop_column('homework', 'insight_key_idea_body')
    op.drop_column('homework', 'insight_key_idea_title')
    op.drop_column('homework', 'insight_references')
    op.drop_column('homework', 'insight_what_needs_understanding')
    # ### end Alembic commands ###
