"""custom question collection name

Revision ID: 11b2f0b2e84e
Revises: e5ffe91c5e71
Create Date: 2026-08-27 05:53:53.223223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b2f0b2e84e'
down_revision: Union[str, None] = 'e5ffe91c5e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_questions', sa.Column('collection_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_questions', 'collection_name')
    # ### end Alembic commands ###
