"""initial schema

Revision ID: 45cda7aaa8ee
Revises: 
Create Date: 2026-08-25 07:39:58.685930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45cda7aaa8ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_label', sa.String(), nullable=False),
    sa.Column('teacher_limit', sa.Integer(), nullable=False),
    sa.Column('student_limit', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chapters',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('board', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ONBOARDING', 'ACTIVE', 'SUSPENDED', name='school_status'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'grade', 'section')
    )
    op.create_table('school_curriculum',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'subject_id')
    )
    op.create_table('subscriptions',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELED', name='subscription_status'), nullable=False),
    sa.Column('renews_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('topics',
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'SCHOOL_ADMIN', 'TEACHER', 'STUDENT', name='role'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'DEACTIVATED', name='user_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_table('assistant_messages',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='chat_role'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_papers',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.Column('board', sa.String(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('question_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('instructions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('allow_internal_choice', sa.Boolean(), nullable=False),
    sa.Column('avoid_duplicate_concepts', sa.Boolean(), nullable=False),
    sa.Column('respect_chapter_weightage', sa.Boolean(), nullable=False),
    sa.Column('avoid_recent_repetition', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATING', 'VALIDATION_FAILED', 'REVIEW', 'FINALIZED', name='question_paper_status'), nullable=False),
    sa.Column('custom_header_text', sa.String(), nullable=True),
    sa.Column('logo_data_uri', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_points',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('roll_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('class_id', 'roll_number')
    )
    op.create_table('teacher_class_assignments',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'class_id', 'subject_id')
    )
    op.create_table('voice_tests',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('completion_window_hours', sa.Integer(), nullable=False),
    sa.Column('target_mode', sa.Enum('WHOLE_CLASS', 'SPECIFIC_STUDENTS', name='assignment_target_mode'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'ACTIVE', 'COMPLETED', 'RESULTS_PROCESSING', 'RESULTS_READY', name='test_status'), nullable=False),
    sa.Column('assigned_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homework',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('gap_topic', sa.Text(), nullable=False),
    sa.Column('gap_mastery_percent', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MIXED', 'HARD', name='homework_difficulty'), nullable=False),
    sa.Column('target_mode', sa.Enum('WHOLE_CLASS', 'SPECIFIC_STUDENTS', name='assignment_target_mode'), nullable=False),
    sa.Column('completion_window_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('GENERATING', 'REVIEW', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='homework_status'), nullable=False),
    sa.Column('assigned_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['voice_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_paper_bloom_distribution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloom_level'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['question_papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'bloom_level')
    )
    op.create_table('question_paper_chapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['question_papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'chapter_id')
    )
    op.create_table('question_paper_dataset_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['question_papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'dataset_id')
    )
    op.create_table('question_paper_difficulty_distribution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='paper_difficulty_level'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['question_papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'level')
    )
    op.create_table('question_paper_questions',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloom_level'), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['question_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_paper_sections',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('marks_each', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['question_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_paper_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['question_papers.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'topic_id')
    )
    op.create_table('question_paper_validation',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('coverage_percent', sa.Integer(), nullable=False),
    sa.Column('marks_accounted_for', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('quality_percent', sa.Integer(), nullable=False),
    sa.Column('issues', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['question_papers.id'], ),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_table('student_test_results',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('mastery_percent', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['voice_tests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'student_id')
    )
    op.create_table('voice_test_bloom_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloom_level'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['voice_tests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'bloom_level')
    )
    op.create_table('voice_test_target_students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['voice_tests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'student_id')
    )
    op.create_table('homework_bloom_distribution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('homework_id', sa.UUID(), nullable=False),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloom_level'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homework_id', 'bloom_level')
    )
    op.create_table('homework_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('homework_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homework_id', 'dataset_id')
    )
    op.create_table('homework_questions',
    sa.Column('homework_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloom_level'), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homework_target_students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('homework_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homework_id', 'student_id')
    )
    op.create_table('retest_attempts',
    sa.Column('homework_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'RESULT_READY', name='student_retest_status'), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('baseline_percent', sa.Integer(), nullable=True),
    sa.Column('retest_percent', sa.Integer(), nullable=True),
    sa.Column('improvement_percent', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homework_id', 'student_id')
    )
    op.create_table('student_homework_progress',
    sa.Column('homework_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', name='student_homework_status'), nullable=False),
    sa.Column('qa_completed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homework_id', 'student_id')
    )
    op.create_table('student_test_result_bloom_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_test_result_id', sa.UUID(), nullable=False),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloom_level'), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_test_result_id'], ['student_test_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_test_result_id', 'bloom_level')
    )
    op.create_table('topic_performance',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('homework_id', sa.UUID(), nullable=False),
    sa.Column('topic_label', sa.Text(), nullable=False),
    sa.Column('before_percent', sa.Integer(), nullable=True),
    sa.Column('after_percent', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['voice_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_assessor_sessions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=True),
    sa.Column('retest_attempt_id', sa.UUID(), nullable=True),
    sa.Column('context_label', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['retest_attempt_id'], ['retest_attempts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['voice_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retest_bloom_comparison',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('retest_attempt_id', sa.UUID(), nullable=False),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloom_level'), nullable=False),
    sa.Column('before', sa.Integer(), nullable=True),
    sa.Column('after', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['retest_attempt_id'], ['retest_attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retest_attempt_id', 'bloom_level')
    )
    op.create_table('ai_assessor_session_bloom_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloom_level'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_assessor_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'bloom_level')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_assessor_session_bloom_levels')
    op.drop_table('retest_bloom_comparison')
    op.drop_table('ai_assessor_sessions')
    op.drop_table('topic_performance')
    op.drop_table('student_test_result_bloom_scores')
    op.drop_table('student_homework_progress')
    op.drop_table('retest_attempts')
    op.drop_table('homework_target_students')
    op.drop_table('homework_questions')
    op.drop_table('homework_datasets')
    op.drop_table('homework_bloom_distribution')
    op.drop_table('voice_test_target_students')
    op.drop_table('voice_test_bloom_levels')
    op.drop_table('student_test_results')
    op.drop_table('question_paper_validation')
    op.drop_table('question_paper_topics')
    op.drop_table('question_paper_sections')
    op.drop_table('question_paper_questions')
    op.drop_table('question_paper_difficulty_distribution')
    op.drop_table('question_paper_dataset_shares')
    op.drop_table('question_paper_chapters')
    op.drop_table('question_paper_bloom_distribution')
    op.drop_table('homework')
    op.drop_table('voice_tests')
    op.drop_table('teacher_class_assignments')
    op.drop_table('student_profiles')
    op.drop_table('student_points')
    op.drop_table('question_papers')
    op.drop_table('audit_logs')
    op.drop_table('assistant_messages')
    op.drop_table('users')
    op.drop_table('topics')
    op.drop_table('subscriptions')
    op.drop_table('school_curriculum')
    op.drop_table('classes')
    op.drop_table('schools')
    op.drop_table('chapters')
    op.drop_table('subjects')
    op.drop_table('plans')
    op.drop_table('datasets')
    # ### end Alembic commands ###
