"""school feature entitlements

Revision ID: 84e596a1a9f2
Revises: 7a1c9e2b4f3d
Create Date: 2026-08-26 14:09:42.592525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84e596a1a9f2'
down_revision: Union[str, None] = '7a1c9e2b4f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('enabled_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'enabled_features')
    # ### end Alembic commands ###
