"""custom question grade level

Revision ID: 94dcb78f75fd
Revises: 11b2f0b2e84e
Create Date: 2026-08-28 03:34:37.342625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94dcb78f75fd'
down_revision: Union[str, None] = '11b2f0b2e84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_questions', sa.Column('grade', sa.Integer(), nullable=True))
    op.alter_column('custom_questions', 'class_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
    # Not autogenerated - alembic's default compare doesn't detect check
    # constraints. Every existing row already has class_id set and grade
    # NULL, so this holds immediately with no backfill needed.
    op.create_check_constraint(
        'custom_questions_class_xor_grade',
        'custom_questions',
        '(class_id IS NOT NULL AND grade IS NULL) OR (class_id IS NULL AND grade IS NOT NULL)',
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('custom_questions_class_xor_grade', 'custom_questions', type_='check')
    op.alter_column('custom_questions', 'class_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('custom_questions', 'grade')
    # ### end Alembic commands ###
