"""school logo

Revision ID: 9efa171049a4
Revises: e31bcf573936
Create Date: 2026-08-27 04:08:28.784554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efa171049a4'
down_revision: Union[str, None] = 'e31bcf573936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('logo_data_uri', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'logo_data_uri')
    # ### end Alembic commands ###
