"""default bloom distribution, general edit fields

Revision ID: ade4f3cd33d7
Revises: f49bba36ac06
Create Date: 2026-08-25 08:36:19.976689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ade4f3cd33d7'
down_revision: Union[str, None] = 'f49bba36ac06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('default_bloom_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'default_bloom_distribution')
    # ### end Alembic commands ###
