"""gamification and journey

Revision ID: f3daf3e7fd76
Revises: 6e2a9c4f1b58
Create Date: 2026-09-11 07:15:31.594433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3daf3e7fd76'
down_revision: Union[str, None] = '6e2a9c4f1b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_chapter_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'chapter_id')
    )
    op.create_table('student_daily_goal_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('goal_key', sa.String(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'goal_key', 'completed_date')
    )
    op.create_table('student_gamification',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('xp_for_next_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.add_column('chapters', sa.Column('order_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Data backfill: give every existing chapter a deterministic
    # order_index within its subject, so the "Journey" map
    # (src/api/routes/journey.py) has a stable DONE/CURRENT/LOCKED
    # sequence from day one instead of every chapter reading as
    # order_index=NULL. `id` isn't sequential (UUID), so this doesn't
    # reproduce a real syllabus order - it only guarantees the order is
    # fixed and doesn't reshuffle between requests. A school/curriculum
    # admin flow to reorder chapters deliberately is separate future work.
    op.execute(
        """
        UPDATE chapters
        SET order_index = ranked.rn
        FROM (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY subject_id ORDER BY id) AS rn
            FROM chapters
        ) AS ranked
        WHERE chapters.id = ranked.id
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'order_index')
    op.drop_table('student_gamification')
    op.drop_table('student_daily_goal_completions')
    op.drop_table('student_chapter_progress')
    # ### end Alembic commands ###
