"""user provisioning, plan limits, catalog metadata

Revision ID: f49bba36ac06
Revises: 45cda7aaa8ee
Create Date: 2026-08-25 07:40:45.449529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49bba36ac06'
down_revision: Union[str, None] = '45cda7aaa8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('test_limit', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('question_paper_limit', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('schools', sa.Column('address', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('principal_name', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('guardian_name', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('guardian_phone', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'phone_number')
    op.drop_column('student_profiles', 'date_of_birth')
    op.drop_column('student_profiles', 'guardian_phone')
    op.drop_column('student_profiles', 'guardian_name')
    op.drop_column('schools', 'principal_name')
    op.drop_column('schools', 'contact_phone')
    op.drop_column('schools', 'address')
    op.drop_column('plans', 'active')
    op.drop_column('plans', 'question_paper_limit')
    op.drop_column('plans', 'test_limit')
    # ### end Alembic commands ###
